name: Build and Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:   
    - cron: '0 12 * * *'

jobs:
  build-and-scan:
    name: Run Tests and SonarCloud
    runs-on: ubuntu-latest
    steps:
      # 1. Faz o checkout do código (fetch-depth: 0 é exigido pelo Sonar)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      # 2. Configura o Node.js
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          
      # 3. Instala dependências (Jest, Pactum, etc.)
      - name: Install Dependencies
        run: npm install      
        
      # 4. Roda os testes e gera a pasta coverage
      - name: Run Tests and Coverage
        run: npm run coverage

      # 5. Envia o código e a cobertura para o SonarCloud
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}